#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
RUN apt-get update \
    && apt-get install -y --no-install-recommends libgdiplus libc6-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["NzCovidPassTelegramBot/NzCovidPassTelegramBot.csproj", "NzCovidPassTelegramBot/"]
RUN dotnet restore "NzCovidPassTelegramBot/NzCovidPassTelegramBot.csproj"
COPY . .
WORKDIR "/src/NzCovidPassTelegramBot"
RUN dotnet build "NzCovidPassTelegramBot.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "NzCovidPassTelegramBot.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
CMD ASPNETCORE_URLS=http://*:$PORT dotnet NzCovidPassTelegramBot.dll